### ISSUE TITLE
Cannot add plugin through browse repositories

### ISSUE THREAD

**Issue by SUPERCILEX** [JetBrains/intellij-stats-collector#1]
Here's the error I'm getting:

List of plugins was not loaded for following hosts: https://plugins.jetbrains.com/plugin/8117

Due to the following errors:
`org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 3; The markup in the document preceding the root element must be well-formed.' for 'https://plugins.jetbrains.com/plugin/8117`

**Comment by lepenkinya** [comment]
Where do you get it? What IDEA version you use?

**Comment by SUPERCILEX** [comment]
I'm using Android Studio which is using build 145.1617.8 of Intellij IDEA.

**Comment by SUPERCILEX** [comment]
This was fixed a while ago I believe.

**Comment by nicklusk** [comment]
It may have been fixed a while ago, but I'm getting it now in WebStorm
