### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by IRus** [JetBrains/intellij-stats-collector#20]
![screenshot from 2018-11-22 14-13-58](https://user-images.githubusercontent.com/493656/48899936-0c938400-ee62-11e8-9131-ea5f7487fb2f.png)

```
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
Licensed to Ruslan Ibragimov
Subscription is active until October 19, 2019
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-38-generic
```

**Comment by IRus** [comment]
Looks like some problem with build, previous versions of plugin was about 4mb, now about 100kb.
![screenshot from 2018-11-22 14-26-50](https://user-images.githubusercontent.com/493656/48900162-af4c0280-ee62-11e8-9d87-0d23d276530d.png)

**Comment by IRus** [comment]
cc @bibaev

**Comment by bibaev** [comment]
Fixed in 0.1.6

**Comment by IRus** [comment]
https://plugins.jetbrains.com/plugin/8117-completion-stats-collector

There are older version which has bigger version number, so Idea reports that there are no updates.

**Comment by IRus** [comment]
Okay, so version `183.4284.148` deleted from plugins repository. I have to manually delete this broken version of plugin, restart IDE, install plugin (0.1.7 this time) and restart IDE again to make it work.

**Comment by BorzdeG** [comment]
version 183.4886.3 - The error is still present

**Comment by IRus** [comment]
> version 183.4886.3 - The error is still present

This is no such version https://plugins.jetbrains.com/plugin/8117-completion-stats-collector

Delete it, and install latest version of plugin
